CREATE TABLE users (
                       id bigint PRIMARY KEY AUTO_INCREMENT,
                       Cpf varchar(11) UNIQUE NOT NULL,
                       name varchar(100) NOT NULL,
                       tel varchar(9),
                       ddd varchar(2),
                       email varchar(30) NOT NULL,
                       password varchar(255),
                       birthday date,
                       creation_date date,
                       zip_code varchar(8),
                       address varchar(150),
                       number varchar(4),
                       additional_info varchar(5),
                       neigborhood varchar(100),
                       state varchar(2),
                       city varchar(30),
                       active TINYINT(1) DEFAULT 1,
                       points INT
);